export const OPEN_SEND_MESSAGE = "OPEN_SEND_MESSAGE";
export const CLOSE_SEND_MESSAGE = "CLOSE_SEND_MESSAGE";

export const SELECT_MAIL = "SELECT_MAIL";

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
